neighbourhood_groups = [
    "AROUCA",
    "ESPINHO",
    "GONDOMAR",
    "MAIA",
    "MATOSINHOS",
    "OLIVEIRA DE AZEMÉIS",
    "PAREDES",
    "PORTO",
    "PÓVOA DE VARZIM",
    "SANTA MARIA DA FEIRA",
    "SANTO TIRSO",
    "SÃO JOÃO DA MADEIRA",
    "TROFA",
    "VALE DE CAMBRA",
    "VALONGO",
    "VILA DO CONDE",
    "VILA NOVA DE GAIA",
]

neighborhoods = [
    "AVer-o-Mar, Amorim e Terroso",
    "Agrela",
    "Aguiar de Sousa",
    "Aguçadoura e Navais",
    "Aldoar, Foz do Douro e Nevogilde",
    "Alfena",
    "Alvarelhos e Guidões",
    "Alvarenga",
    "Anta e Guetim",
    "Arcozelo",
    "Areias, Sequeiró, Lama e Palmeira",
    "Argoncilhe",
    "Arouca e Burgo",
    "Arrifana",
    "Arões",
    "Aveleda",
    "Avintes",
    "Azurara",
    "Baguim do Monte (Rio Tinto)",
    "Bagunte, Ferreiró, Outeiro Maior e Parada",
    "Balazar",
    "Baltar",
    "Bonfim",
    "Bougado (São Martinho e Santiago)",
    "Cabreiros e Albergaria da Serra",
    "Caldas de São Jorge e de Pigeiros",
    "Campanhã",
    "Campo e Sobrado",
    "Canedo, Vale e Vila Maior",
    "Canelas",
    "Canelas e Espiunca",
    "Canidelo",
    "Carregosa",
    "Carreira e Refojos de Riba de Ave",
    "Castêlo da Maia",
    "Cedofeita, Ildefonso, Sé, Miragaia, Nicolau, Vitória",
    "Cepelos",
    "Cesar",
    "Cete",
    "Chave",
    "Cidade da Maia",
    "Coronado (São Romão e São Mamede)",
    "Covelas",
    "Covelo de Paivó e Janarde",
    "Cristelo",
    "Custóias, Leça do Balio e Guifões",
    "Duas Igrejas",
    "Ermesinde",
    "Escariz",
    "Espinho",
    "Estela",
    "Fajões",
    "Fermedo",
    "Fiães",
    "Fornelo e Vairão",
    "Fornos",
    "Foz do Sousa e Covelo",
    "Fânzeres e São Pedro da Cova",
    "Gandra",
    "Gião",
    "Gondomar (São Cosme), Valbom e Jovim",
    "Grijó e Sermonde",
    "Guilhabreu",
    "Gulpilhares e Valadares",
    "Junqueira",
    "Labruge",
    "Laundos",
    "Lobão, Gião, Louredo e Guisande",
    "Lomba",
    "Lordelo do Ouro e Massarelos",
    "Louredo",
    "Lourosa",
    "Macieira da Maia",
    "Macieira de Cambra",
    "Macieira de Sarnes",
    "Madalena",
    "Mafamude e Vilar do Paraíso",
    "Malta e Canidelo",
    "Mansores",
    "Matosinhos e Leça da Palmeira",
    "Melres e Medas",
    "Milheirós",
    "Milheirós de Poiares",
    "Mindelo",
    "Moldes",
    "Monte Córdova",
    "Moreira",
    "Mozelos",
    "Muro",
    "Negrelos (São Tomé)",
    "Nogueira da Regedoura",
    "Nogueira do Cravo e Pindelo",
    "Nogueira e Silva Escura",
    "O. Azeméis, Riba-Ul, Ul, Macinhata da Seixa, Madail",
    "Oliveira do Douro",
    "Ossela",
    "Parada de Todeia",
    "Paramos",
    "Paranhos",
    "Paredes",
    "Paços de Brandão",
    "Pedroso e Seixezelo",
    "Pedrouços",
    "Perafita, Lavra e Santa Cruz do Bispo",
    "Pinheiro da Bemposta, Travanca e Palmaz",
    "Póvoa de Varzim, Beiriz e Argivai",
    "Ramalde",
    "Rates",
    "Rebordosa",
    "Reguenga",
    "Retorta e Tougues",
    "Rio Mau e Arcos",
    "Rio Tinto",
    "Roge",
    "Romariz",
    "Roriz",
    "Rossas",
    "Sandim, Olival, Lever e Crestuma",
    "Sanguedo",
    "Santa Eulália",
    "Santa Maria da Feira, Travanca, Sanfins e Espargo",
    "Santa Maria de Lamas",
    "Santa Marinha e São Pedro da Afurada",
    "Serzedo e Perosinho",
    "Silvalde",
    "Sobreira",
    "St. Tirso, Couto (S. Cristina e S. Miguel) e Burgães",
    "São Félix da Marinha",
    "São João da Madeira",
    "São Mamede de Infesta e Senhora da Hora",
    "São Martinho da Gândara",
    "São Miguel do Mato",
    "São Pedro Fins",
    "São Pedro de Castelões",
    "São Roque",
    "Touguinha e Touguinhó",
    "Tropeço",
    "Urrô",
    "Valongo",
    "Vandoma",
    "Vila Chã",
    "Vila Chã, Codal e Vila Cova de Perrinho",
    "Vila Nova da Telha",
    "Vila Nova do Campo",
    "Vila de Cucujães",
    "Vila do Conde",
    "Vilar de Andorinho",
    "Vilar de Pinheiro",
    "Vilar e Mosteiró",
    "Vilarinho",
    "Vilela",
    "Várzea",
    "Água Longa",
    "Águas Santas",
    "Árvore",
]

room_types = ["Entire home/apt", "Hotel room", "Private room", "Shared room"]
