descriptions_of_columns = [
    ("absorvente", "Absorvente"),
    ("acetona", "Acetona"),
    ("achocolatado", "Achocolatado"),
    ("acucar", "Açúcar"),
    ("adocante", "Adoçante"),
    ("agua_oxigenada", "Água oxigenada"),
    ("agua", "Água"),
    ("agulheiro", "Agulheiro"),
    ("algodao", "Algodão"),
    ("amendoim", "Amendoim"),
    ("amonia", "Amônia"),
    ("anilina", "Anilina"),
    ("apresuntado", "Apresuntado"),
    ("arroz", "Arroz"),
    ("azeitona", "Azeitona"),
    ("bala", "Bala"),
    ("balao", "Balão"),
    ("band_aid", "Band-aid"),
    ("batata_palha", "Batata palha"),
    ("bebida_alcoolica", "Bebida alcoólica"),
    ("bebidas_sem_alcool", "Bebidas sem álcool"),
    ("biscoito", "Biscoito"),
    ("bolos", "Bolos"),
    ("bombom", "Bombom"),
    ("cafe", "Café"),
    ("caixa_de_isopor", "Caixa de isopor"),
    ("canjica", "Canjica"),
    ("canjiquinha", "Canjiquinha"),
    ("canudo", "Canudo"),
    ("carne_seca", "Carne seca"),
    ("carne_bovina", "Carne bovina"),
    ("carne_suina", "Carne suína"),
    ("carvao", "Carvão"),
    ("cereal", "Cereal"),
    ("cha", "Chá"),
    ("chinelo", "Chinelo"),
    ("chocolate", "Chocolate"),
    ("coco_ralado", "Coco ralado"),
    ("comida_congelada", "Comida congelada"),
    ("comida_pet", "Comida de pet"),
    ("cortador_de_unha", "Cortador de unha"),
    ("cortina", "Cortina"),
    ("cotonete", "Cotonete"),
    ("creme_de_leite", "Creme de leite"),
    ("creme", "Creme"),
    ("desodorante", "Desodorante"),
    ("doce", "Doce"),
    ("ducha", "Ducha"),
    ("embutidos", "Embutidos"),
    ("energetico", "Energético"),
    ("esmalte", "Esmalte"),
    ("esparadrapo", "Esparadrapo"),
    ("especiarias", "Especiarias"),
    ("espelho", "Espelho"),
    ("espuma_de_barbear", "Espuma de barbear"),
    ("extensao", "Extensão"),
    ("extrato_de_tomate", "Extrato de tomate"),
    ("farinha", "Farinha"),
    ("farofa", "Farofa"),
    ("feijao", "Feijão"),
    ("fermento", "Fermento"),
    ("frutas", "Frutas"),
    ("fuba", "Fuba"),
    ("gelatina", "Gelatina"),
    ("geleia", "Geleia"),
    ("gel", "Gel"),
    ("goiabada", "Goiabada"),
    ("gordura_vegetal", "Gordura vegetal"),
    ("graxa_de_sapato", "Graxa de sapato"),
    ("guarda_chuva", "Guarda-chuva"),
    ("guardanapo", "Guardanapo"),
    ("hamburguer", "Hambúrguer"),
    ("inseticida", "Inseticida"),
    ("iogurte", "Iogurte"),
    ("isqueiro", "Isqueiro"),
    ("lamina", "Lâmina"),
    ("lampada", "Lampada"),
    ("legumes_em_lata", "Legumes em lata"),
    ("legumes", "Legumes"),
    ("leite_condensado", "Leite condensado"),
    ("leite_de_coco", "Leite de coco"),
    ("leite", "Leite"),
    ("limpeza_de_pele", "Limpeza de pele"),
    ("limpeza_de_roupas", "Limpeza de Roupas"),
    ("lixa_para_unha", "Lixa para unha"),
    ("macarrao", "Macarrão"),
    ("maionese", "Maionese"),
    ("maisena", "Maisena"),
    ("manteiga", "Manteiga"),
    ("marmita", "Marmita"),
    ("massa_preparo", "Massa preparo"),
    ("material_escolar", "Material escolar"),
    ("meia_infantil", "Meia infantil"),
    ("milho_de_pipoca", "Milho de pipoca"),
    ("mistura_de_bolo", "Mistura de bolo"),
    ("molho", "Molho"),
    ("mortadela", "Mortadela"),
    ("naftalina", "Naftalina"),
    ("odorizante", "Odorizante"),
    ("oleo_de_maquina", "Óleo de máquina"),
    ("oleo_vegetal", "Óleo vegetal"),
    ("ovo", "Ovo"),
    ("pacoca", "Paçoca"),
    ("paes", "Pães"),
    ("palito_para_unhas", "Palito para unhas"),
    ("palito", "Palito"),
    ("palmito", "Palmito"),
    ("papel_aluminio", "Papel alumínio"),
    ("papel_higienico", "Papel higiênico"),
    ("peixe_em_lata", "Peixe em lata"),
    ("pente", "Pente"),
    ("pessego_em_calda", "Pêssego em calda"),
    ("pilha", "Pilha"),
    ("polvilho_antisseptico", "Polvilho antisséptico"),
    ("prestobarba", "Prestobarba"),
    ("presunto", "Presunto"),
    ("produtos_de_banho", "Produtos de banho"),
    ("produtos_de_bebe", "Produtos de bebe"),
    ("produtos_de_frango", "Produtos de frango"),
    ("produtos_de_limpeza", "Produtos de limpeza"),
    ("produtos_de_odonto", "Produtos de odonto"),
    ("produtos_de_peixes", "Produtos de peixes"),
    ("queijos", "Queijos"),
    ("querosene", "Querosene"),
    ("refrigerante", "Refrigerante"),
    ("requeijao", "Requeijão"),
    ("rosca", "Rosca"),
    ("saco_plastico", "Saco plástico"),
    ("sal", "Sal"),
    ("sopa", "Sopa"),
    ("sorvete", "Sorvete"),
    ("suco", "Suco"),
    ("tabaco", "Tabaco"),
    ("tapete", "Tapete"),
    ("tintura", "Tintura"),
    ("toalha_de_banho", "Toalha de banho"),
    ("torneira", "Torneira"),
    ("torrada", "Torrada"),
    ("trigo_de_quibe", "Trigo de quibe"),
    ("utensilios_de_cozinha", "Utensílios de cozinha"),
    ("veda_rosca", "Veda rosca"),
    ("vela_de_filtro", "Vela de filtro"),
    ("vela", "Vela"),
    ("verduras", "Verduras"),
    ("vinagre", "Vinagre"),
]


def columns_labels() -> list[str]:
    return [label for label, _ in descriptions_of_columns]


def columns_names() -> list[str]:
    return [name for _, name in descriptions_of_columns]
